version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokemons
    volumes:
      - /tmp/postgres/parcelamos/payment-link:/var/lib/postgresql/data
