# fly.toml app configuration file generated for pokemons-api-fragrant-star-3436 on 2024-02-24T16:05:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokemons-api-fragrant-star-3436'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "npm run migrations:dev"
